title: Kangyu Wang 王康予
logo: assets/logo.png
headshot: assets/Kevin_photo.jpg
description: A bit of space to record a bit too many things.
email: k[dot]wang37[at]lse.ac.uk

github: https://github.com/KevHH
linkedin: https://www.linkedin.com/in/kevin-han-huang-995ab1a0/
arxiv: https://arxiv.org/a/0000-0002-9534-7239.html
gscholar: https://scholar.google.com/citations?hl=en&user=eJXepUMAAAAJ

# specify navigation / menu bar
nav:
  item1:
    title: About Me
    url: /
  item2:
    title: Research
    url: /research
  item3:
    title: Teaching
    url: /teaching
  item4: 
    title: '&#123; x ∉ Maths &#125;'
    url: /non-maths
  item5:
    title: Collection
    url: /collection
