title: Kangyu Wang 王康予
logo: assets/logo.png
headshot: assets/KY_photo.jpg
description: A bit of space to record a bit too many things.
email: k[dot]wang37[at]lse.ac.uk

linkedin: https://www.linkedin.com/in/kangyu-wang-2469931a1/
philpeople: https://philpeople.org/profiles/kangyu-wang

# specify navigation / menu bar
nav:
  item1:
    title: About Me
    url: /
  item2:
    title: Research
    url: /research
  item3:
    title: Talks
    url: /talks
  item4: 
    title: Teaching
    url: /teaching
  item5:
    title: Services & Other Affliations
    url: /services-affiliations
