#
#    Docker-compose file for GitHub Page
#

version: '3'

services:
  github-page:
    image: github-page-docker
    volumes:
      - './:/srv/jekyll'
      - /srv/jekyll/_site/
    ports:
      - '4000:4000'
      - '35729:35729'