
version: '3'

services:
  github-page:
    image: ghcr.io/kevhh/jekyll-tailwind:4.1.1
    volumes:
      - './:/srv/jekyll'
      - /srv/jekyll/_site/
    ports:
      - '4000:4000'
      - '35729:35729'