
version: '3'

services:
  github-page:
    image: ghcr.io/bfe-technology/jekyll-tailwind:4.1.1
    volumes:
      - './:/srv/jekyll'
    entrypoint: sh -c "mv -f /srv/jekyll2/* /srv/jekyll && yarn build"