name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
    steps:
      - name: Checkout
        run: |
          git config --global user.email "git@github.com"
          git config --global user.name "KevHH"
          git config --global credential.helper store
          git clone -b dev https://KevHH:$GH_TOKEN@github.com/KevHH/personal-page dev
          git clone -b prod https://KevHH:$GH_TOKEN@github.com/KevHH/personal-page prod

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: KevHH 
          password: ${{ secrets.GH_TOKEN }}

      - name: build
        working-directory: dev
        run: |
          chmod -R 777 .
          docker-compose -f docker-compose-prod.yml up
          find . -regex  "_site\\\\(.*\.json|.*\.config\.js|.*\.yml|.*\.lock|README.md)" -delete

      - name: move build to prod
        run: |
          rm -rf prod/*
          cp -r dev/_site/* prod
          cd prod
          code=$(git diff --quiet)
          if [ "$code" == 1 ]; then
            git add . && git commit -m "build" && git push origin 
          else
            git diff --exit-code
          fi            
