name: Fetch weather
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  fetch-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Update weather icon

