name: Fetch weather
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  fetch-weather:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
    steps:
      - name: Checkout
        run: |
          git config --global user.email "git@github.com"
          git config --global user.name "KevHH"
          git config --global credential.helper store
          git clone https://KevHH:$GH_TOKEN@github.com/KevHH/personal-page .
          
      - name: Update DNS
        run: |
          sudo chown -R runner:runner /run/systemd/resolve/stub-resolv.conf
          sudo echo nameserver 8.8.8.8 >> /run/systemd/resolve/stub-resolv.conf

      - name: Update weather
        run: |
          url=$(curl https://weatherdbi.herokuapp.com/data/weather/shantou | jq -r '.currentConditions.iconURL')
          curl $url -o assets/weather.png
          comment=$(curl https://weatherdbi.herokuapp.com/data/weather/shantou | jq -r '.currentConditions.comment')
          sed -i -e "s,alt=\"[^\"]*\" ,alt=\"$comment\" ,g" ./text/footer.md
      
      - name: Commit  #no commit if last amendment is not by bot, in which case one can only manual override
        run: |
          lastmsg=$(git log -1 --pretty=%B | xargs)
          if [ "$lastmsg" = "weatherbot" ] 
          then
            git add . && git commit --amend -m "weatherbot" && git push origin
          elif [ "${{github.event_name}}" = "workflow_dispatch" ] 
          then
            git add . && git commit -m "weatherbot" && git push origin
          fi
