name: Fetch weather
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  fetch-weather:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
    steps:
      - name: Checkout
        run: |
          git config --global user.email "git@github.com"
          git config --global user.name "KevHH"
          git config --global credential.helper store
          git clone https://KevHH:$GH_TOKEN@github.com/KevHH/personal-page .

      - name: Update weather icon
        run: |
          url=$(curl https://weatherdbi.herokuapp.com/data/weather/shantou | jq '.currentConditions.iconURL')
          sed -i -e "s,src=\"[^\"]*\",src=\"$url\",g" ./text/footer.md
      
      - name: Commit  #no commit if last amendment is not by bot, in which case one can only manual override
        run: |
          git log -1 --pretty=%B | xargs
          last_message=$(git log -1 --pretty=%B | xargs)
          if ( $last_message = "weatherbot" ); then 
            git commit --amend -m "weatherbot" && git add . && git push origin
          else
            if ( "${{github.event_name}}" = "workflow_dispatch"); then
              git commit -m "weatherbot" && git add . && git push origin
            fi
          fi
          

