name: Fetch weather
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  

jobs:
  fetch-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Update weather icon
        run: |
          sudo apt update
          sudo apt install jq
          curl https://weatherdbi.herokuapp.com/data/weather/shantou | jq '.iconURL'

